SELECT * FROM TBL_FOLLOW ;
SELECT * FROM TBL_USER;

/*팔로우 카운트 뷰*/
SELECT * FROM VIEW_FOLLOW ;

/*시퀀스 생성*/
CREATE SEQUENCE SEQ_FOLLOW;

/*팔로우 테이블*/
CREATE TABLE TBL_FOLLOW
(
	FOLLOW_ID NUMBER CONSTRAINT PK_FOLLOW PRIMARY KEY,
	FOLLOWING_ID NUMBER NOT NULL,
	FOLLOWED_ID NUMBER NOT NULL,
	FOLLOW_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_FOLLOWING FOREIGN KEY(FOLLOWING_ID) REFERENCES TBL_USER(USER_ID),
	CONSTRAINT FK_FOLLOWED FOREIGN KEY(FOLLOWED_ID) REFERENCES TBL_USER(USER_ID)	
);

/*팔로우 카운트 뷰*/
CREATE VIEW VIEW_FOLLOW AS 
(
SELECT FI.FID, FI.COUNT_FI, FD.COUNT_FD
FROM (SELECT FOLLOWING_ID FID, COUNT(FOLLOWING_ID) COUNT_FI 
	FROM TBL_FOLLOW F1
	GROUP BY FOLLOWING_ID) FI JOIN
	(SELECT FOLLOWED_ID FID, COUNT(FOLLOWED_ID) COUNT_FD 
	FROM TBL_FOLLOW F2
	GROUP BY FOLLOWED_ID) FD
ON FI.FID = FD.FID
);

/*유저별 팔로잉 수(조인)*/
SELECT USER_ID, COUNT(FOLLOWING_ID)
FROM
	TBL_FOLLOW F JOIN TBL_USER U ON F.FOLLOWING_ID = U.USER_ID 
GROUP BY
	USER_ID;

/*유저별 팔로우 받은 수(조인)*/
SELECT USER_ID, COUNT(FOLLOWED_ID)
FROM
	TBL_FOLLOW F JOIN TBL_USER U ON F.FOLLOWED_ID = U.USER_ID 
GROUP BY
	USER_ID;

/*유저별 팔로잉 수(조인X)*/
SELECT FOLLOWING_ID, COUNT(FOLLOWING_ID) 
FROM TBL_FOLLOW F
GROUP BY FOLLOWING_ID;

/*유저별 팔로우 받은 수(조인X)*/
SELECT FOLLOWED_ID, COUNT(FOLLOWED_ID) 
FROM TBL_FOLLOW F
GROUP BY FOLLOWED_ID;

/*USER_ID별 팔로잉, 팔로워 수*/
SELECT FI.FID, FI.COUNT_FI, FD.COUNT_FD
FROM (SELECT FOLLOWING_ID FID, COUNT(FOLLOWING_ID) COUNT_FI 
	FROM TBL_FOLLOW F1
	GROUP BY FOLLOWING_ID) FI JOIN
	(SELECT FOLLOWED_ID FID, COUNT(FOLLOWED_ID) COUNT_FD 
	FROM TBL_FOLLOW F2
	GROUP BY FOLLOWED_ID) FD
ON FI.FID = FD.FID;

/*SELECT COUNT(FOLLOW_ID) FROM TBL_FOLLOW F
GROUP BY FOLLOWING_ID ;*/

/*SELECT * FROM TBL_USER
WHERE USER_ID = (
	SELECT FOLLOWING_ID FROM TBL_FOLLOW
	WHERE FOLLOWED_ID = ?
);*/

/*DELETE FROM TBL_FOLLOW
WHERE FOLLOWING_ID = ? AND FOLLOWED_ID = ?;*/

/*DROP TABLE TBL_FOLLOW ;*/