CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_REPLY(
	REPLY_ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR2(1000) NOT NULL,
	REPLY_REGISTER_DATE DATE DEFAULT SYSDATE,
	REPLY_UPDATE_DATE DATE DEFAULT SYSDATE,
	USER_ID NUMBER NOT NULL,
	BOARD_ID NUMBER NOT NULL,
	REPLY_GROUP NUMBER NOT NULL,
	REPLY_DEPTH NUMBER NOT NULL,
	CONSTRAINT FK_REPLY_USER FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID) ON DELETE CASCADE,
	CONSTRAINT FK_REPLY_BOARD FOREIGN KEY(BOARD_ID) REFERENCES TBL_BOARD(BOARD_ID) ON DELETE CASCADE
);

SELECT * FROM TBL_REPLY tr ;

INSERT INTO TBL_REPLY
(REPLY_ID, REPLY_CONTENT, REPLY_REGISTER_DATE, REPLY_UPDATE_DATE, USER_ID, BOARD_ID, REPLY_GROUP, REPLY_DEPTH)
VALUES(1, '댓글테스트1', SYSDATE, SYSDATE, 1, 1, 1, 0);

SELECT LEVEL, LPAD('	',REPLY_DEPTH*5) || REPLY_CONTENT 계층화, USER_ID 유저번호, REPLY_GROUP "원댓글번호" 
FROM TBL_REPLY R 
CONNECT BY PRIOR REPLY_GROUP = REPLY_GROUP;